-- MySQL 8.x schema for Student API
CREATE DATABASE IF NOT EXISTS StudentDb;
CREATE USER IF NOT EXISTS 'student_user'@'%' IDENTIFIED BY 'ChangeMe!234';
GRANT ALL PRIVILEGES ON StudentDb.* TO 'student_user'@'%';
FLUSH PRIVILEGES;

USE StudentDb;
CREATE TABLE IF NOT EXISTS Students (
  Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(200) NOT NULL,
  Email VARCHAR(200) NOT NULL,
  Age INT NOT NULL
);
